#ifndef LIBGAZE_EYETRACKER_DEFINES_H_
#define LIBGAZE_EYETRACKER_DEFINES_H_



enum eyetracker_modes{
	EYETRACKER_MODE_NORMAL,
	EYETRACKER_MODE_DUMMY,
};


enum eyetracker_return{
	LG_EYETRACKER_OK,
	LG_EYETRACKER_ERROR,
	LG_EYETRACKER_COULD_NOT_FIND_MODULE,
	LG_EYETRACKER_WRONG_MODULE,
	LG_EYETRACKER_COULD_NOT_LOAD_MODULE,
	LG_EYETRACKER_COULD_NOT_START_TRACKING,
	LG_EYETRACKER_IS_NOT_TRACKING,		
	LG_EYETRACKER_NEW_DATA,
	LG_EYETRACKER_NO_NEW_DATA_AVAILABLE,
	LG_EYETRACKER_NO_DATA_AVAILABLE,		
	LG_EYETRACKER_REQUESTED_EYE_NOT_TRACKED,
	LG_EYETRACKER_COULD_NOT_CONNECT,	
	LG_EYETRACKER_NOT_CONNECTED,
	LG_EYETRACKER_IS_CONNECTED,
	LG_EYETRACKER_CFG_FILE_FORMAT_ERROR,		
	LG_EYETRACKER_COULD_NOT_FIND_CFG_FILE,
	LG_EYETRACKER_IS_NOT_CONFIGURED,
	LG_EYETRACKER_NO_LOG_FILE_OPEN,					
	LG_EYETRACKER_COULD_NOT_OPEN_LOG_FILE,
	LG_EYETRACKER_COULD_NOT_CLOSE_LOG_FILE,
	LG_EYETRACKER_COULD_NOT_ADD_LOG_MSG
};


#endif /*LIBGAZE_EYETRACKER_DEFINES_H_*/
