CC = gcc

INCLUDES+=	-I"$(MINGWPATH)/include/glib-2.0" \
			-I"$(MINGWPATH)/lib/glib-2.0/include" \

#CFLAGS= -shared -fpic -O2 -Wl,--output-def,lib/libgaze.def,--out-implib,lib/libgaze.dll --export-all-symbols 

LIBEXT = .dll

include makefile.config

	