CC = gcc

LIBGAZE_INCLUDE=include/libGaze

INCLUDES+=	-I"$(LIBGAZE_INCLUDE)"
						#-I"include"

#LINKLIBS=	-ldl \
#			-lgd \
#			-lparse_conf  
CFLAGS= -Wall



LIBNAME = libgaze

	
SRCDIR = src/
OBJDIR = bin/
				
SRCS = 	libGaze.c \
		eyetracker/libGaze_eyetracker.c \
		eyetracker/libGaze_eyetracker_fixation.c \
		libGaze_error.c \
		headtracker/libGaze_headtracker.c \
		display/libGaze_display.c \
		calibration/libGaze_calibration.c \
		libGaze_anti_eye_fixation.c \
		libGaze_head_fixation.c \
		gazetracker/libGaze_gazetracker.c \
		gazetracker/libGaze_gazetracker_logging.c \
		gazetracker/libGaze_gazetracker_saveloadcalib.c \
		gazetracker/libGaze_gazetracker_calibration.c \
		gazetracker/libGaze_gazetracker_grid.c \
		gazetracker/libGaze_gazetracker_fixations.c \
		gazetracker/libGaze_gazetracker_instructions.c \
		visualisation/libGaze_visualisation.c \
		tools/libGaze_tools.c \
		tools/libGaze_vector_and_angles.c \
		tools/libGaze_matrix.c \
		headtracker/libGaze_headtracker_logging.c \
		eyetracker/libGaze_eyetracker_logging.c

HEADERS = 	$(LIBGAZE_INCLUDE)/libGaze_api.h \
			$(LIBGAZE_INCLUDE)/libGaze_defines.h \
			$(LIBGAZE_INCLUDE)/libGaze_error.h \
			$(LIBGAZE_INCLUDE)/libGaze_fixations.h \
			$(LIBGAZE_INCLUDE)/libGaze_input_types.h \
			$(LIBGAZE_INCLUDE)/libGaze_keys.h \
			$(LIBGAZE_INCLUDE)/libGaze_time.h \
			$(LIBGAZE_INCLUDE)/libGaze_types.h \
			$(LIBGAZE_INCLUDE)/libGaze.h \
			$(LIBGAZE_INCLUDE)/calibration/libGaze_calibration_types.h \
			$(LIBGAZE_INCLUDE)/calibration/libGaze_calibration.h \
			$(LIBGAZE_INCLUDE)/display/libGaze_display_types.h \
			$(LIBGAZE_INCLUDE)/display/libGaze_display.h \
			$(LIBGAZE_INCLUDE)/gazetracker/libGaze_gazetracker_defines.h \
			$(LIBGAZE_INCLUDE)/gazetracker/libGaze_gazetracker_types.h \
			$(LIBGAZE_INCLUDE)/gazetracker/libGaze_gazetracker.h \
			$(LIBGAZE_INCLUDE)/gazetracker/libGaze_gazetracker_logging.h \
			$(LIBGAZE_INCLUDE)/eyetracker/libGaze_eyetracker_defines.h \
			$(LIBGAZE_INCLUDE)/eyetracker/libGaze_eyetracker_types.h \
			$(LIBGAZE_INCLUDE)/eyetracker/libGaze_eyetracker_fixation.h \
			$(LIBGAZE_INCLUDE)/eyetracker/libGaze_eyetracker_logging.h \
			$(LIBGAZE_INCLUDE)/eyetracker/libGaze_eyetracker.h \
			$(LIBGAZE_INCLUDE)/headtracker/libGaze_headtracker_defines.h \
			$(LIBGAZE_INCLUDE)/headtracker/libGaze_headtracker_types.h \
			$(LIBGAZE_INCLUDE)/headtracker/libGaze_headtracker_logging.h \
			$(LIBGAZE_INCLUDE)/headtracker/libGaze_headtracker.h \
			$(LIBGAZE_INCLUDE)/visualisation/libGaze_visualisation.h \
			$(LIBGAZE_INCLUDE)/visualisation/libGaze_visualisation_types.h \
			$(LIBGAZE_INCLUDE)/tools/libGaze_matrix.h \
			$(LIBGAZE_INCLUDE)/tools/libGaze_tools.h \
			$(LIBGAZE_INCLUDE)/tools/libGaze_vector_and_angles.h
							
OBJS = $(SRCS:%.c=%.o)
OBJ=$(OBJS:%=$(OBJDIR)%)
SRC=$(SRCS:%=$(SRCDIR)%)

all: $(OBJ)
	ar rcs lib/$(LIBNAME)$(LIBEXT) $(OBJ)
	ranlib lib/$(LIBNAME)$(LIBEXT)
	
$(OBJDIR)%.o: $(SRCDIR)%.c $(HEADERS)
	$(CC) $(CFLAGS) -o $@ -c $< $(INCLUDES)

clean:
	rm -rf  $(OBJ) lib/$(LIBNAME)$(LIBEXT)

	