LINKLIBS +=	-lparse_conf\
			-leyelink_core\
			-lglib-2.0\
			-lgthread-2.0

			
#INCLUDES += 



LIBNAME = libeyelink_2


SRCDIR = src/
OBJDIR = bin/

SRC = $(SRCDIR)eyelink_2.c\
			 $(SRCDIR)eyelink_2_config.c\
			 $(SRCDIR)eyelink_2_hooks.c\
			 $(SRCDIR)eyelink_2_error.c\
			 $(SRCDIR)eyelink_2_cam_image.c\
			 $(SRCDIR)eyelink_2_logging.c

HEADERS= 	$(SRCDIR)eyelink_2.h\
			  		$(SRCDIR)eyelink_2_types.h\
			  		$(SRCDIR)eyelink_2_hooks.h\
			  		$(SRCDIR)eyelink_2_error.h\
			  		$(SRCDIR)eyelink_2_cam_image.h\
			  		$(SRCDIR)eyelink_2_logging.h


all: $(SRC) $(HEADERS)
	$(CC)  $(CFLAGS) -o lib/$(LIBNAME)$(LIBEXT) $(SRC)  $(LINKLIBS) $(INCLUDES)

clean:
	-rm -rf  lib/$(LIBNAME)$(LIBEXT)
	